#+Title: Frequently Asked Questions
#+Author: Prakash and Amulya

#+OPTIONS:toc :nil

- How to give read-write-execute permissions to a file?
chmod 0777 fileName

- What is mongodb? Why should I install it?
MongoDB is a document database that provides high performance, high availability, and easy scalability. Documents (objects) map nicely to programming language data types.

- What is the use of 'backports.ssl_match_hostname' package in Python?

The Secure Sockets layer is only actually secure if you check the hostname in the certificate returned by the server to which you are connecting, and verify that it matches to hostname that you are trying to reach.
The ssl package in the Standard Library of Python 3.2 and greater now includes a match_hostname() function for performing this check instead of requiring every application to implement the check separately.

- What is meant by OpenVZ?
OpenVZ  is an operating system-level virtualization technology based on the Linux kernel and operating system. OpenVZ allows a physical server to run multiple isolated operating system instances, called containers or Virtual Environments.

- What is Python sh module?
Sh is a full-fledged subprocess replacement for Python 2.6 - 3.2 that allows you to call any program as if it were a function.

- What is Python netaddr module?
netaddr is a Python library for representing and manipulating network addresses.

- What is the use of Python tornado ?
Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed. By using non-blocking network I/O, Tornado can scale to tens of thousands of open connections, making it ideal for long polling, WebSockets, and other applications that require a long-lived connection to each user.

- I got an error like,
'No module named requests' What should I do now?
You can install python modules either downloading tar and extracting it (or) by using pip, by running the command,
pip install requests

- What is requests module in Python?
Requests is an Apache2 Licensed HTTP library, written in Python.

- How do I install pip in centos?
We can install pip using package manager or by downloading get-pip.py and running it.

Using Package manager :
sudo yum install python-pip

- How can I copy file from remote system ?
We can copy file from remote system using scp. 

scp path-to-source-file user@ip:/path-to-destination

- How can I set http proxy?
export http_proxy="http://proxy-url:8080"

- I was not able to run OVPL.

- How can I install packages using package manager ?
yum install required package.

- I was getting error saying, Permission Denied. What should I do?
Try running the command with sudo.
For example, 
sudo yum install pip

- While running AdapterServer.py, I was getting error stating that, AdapterServer is running already. How should I kill that process ?
ps -ef |grep "AdapterServer"

From here, capture the process and kill the process,
kill -9 process-id

